# Metadata
name: mt_fcgformer

# Class to construct
init:
  _target_: models.mt_fcgformer.MultiTokenFCGFormer

# hyperparameters
spectrum_dim: 1024

patch_size: 16
embed_dim: 496
num_layers: 2
expansion_factor: 4
n_heads: 8
dropout_p: 0.18