model:
  name: mt_fcgformer
  init:
    _target_: models.mt_fcgformer.MultiTokenFCGFormer
  spectrum_dim: 1024
  patch_size: 8
  embed_dim: 256
  num_layers: 3
  expansion_factor: 2
  n_heads: 4
  dropout_p: 0.008943099541295144
metric_output_file: ./trials/phase2_trial_23/metrics.json
skip_checkpoints: true
dataset_id: 157d4b53c95f4af88ee86fbcc319bce2
dataset_name: Shiyi-nist+chemotion+graphormer+rdk+LSER
fg_names:
- alkane
- methyl
- alkene
- alkyne
- alcohols
- amines
- nitriles
- aromatics
- alkyl halides
- esters
- ketones
- aldehydes
- carboxylic acids
- ether
- acyl halides
- amides
- nitro
aux_bool_names: []
aux_float_names: []
nist_weight: 1.0
nist_lser_weight: 0.0
chemmotion_weight: 0.0
chemmotion_lser_weight: 0.0
graphformer_weight: 0.0
graphformer_lser_weight: 0.0
trainer:
  lr: 0.0006779437795864471
  epochs: 200
  batch_size: 128
  patience: 100
  patience_threshold: 0.1
  weight_decay: 0.0033792444912131778
  warmup_steps: 577
  scheduler_t0: 30
  scheduler_tmult: 2
  checkpoint_interval_epochs: 2
  log_interval_steps: 100
  validator:
    batch_size: 32
    threshold: 0.5
mode: train
checkpoint: null
device: cuda:0
runs_path: ./runs
experiment_name: fcg-mt-best
use_noise: true
use_mask: true
use_shiftud: true
use_shiftlr: false
use_revert: true