defaults:
  - model: ircnn
  - dataset: ftir
  - trainer: default
  - evaluator: default
  - predictor: default
  - _self_

mode: train
device: cpu
run_path: ./runs
experiment_name: functional-group-detection
model_name: ${model}_${dataset} # we version models per dataset