# Models use configs for auto-instantiation of objects, so those have strict structure
defaults:
  - model: ircnn
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null

# The MLFlow run id of the dataset
dataset_id: fb3df43da2284161aee9f043a1a4ab33 # FTIR_original
dataset_name: null
fg_names: [alkane, methyl, alkene, alkyne, alcohols, amines, nitriles, aromatics, alkyl halides, esters, ketones, aldehydes, carboxylic acids, ether, acyl halides, amides, nitro]
aux_bool_names: []
aux_float_names: []

# weight accross datasets
# these should probablt be derived for hyperparam opt
nist_weight: 1.0
nist_lser_weight: 0.2

chemmotion_weight: 0.5
chemmotion_lser_weight: 0.1

graphformer_weight: 0.2
graphformer_lser_weight: 0.2

# on top of source weight, multiply lser samples by this
lser_ratio: 0.3

trainer:
  lr: 1e-3
  epochs: 200
  batch_size: 32
  patience: 100 # stop training if validation loss does not improve for x subsequent epochs
  patience_threshold: 0.1

  scheduler_t0: 40
  scheduler_tmult: 2

  checkpoint_interval_epochs: 2 # checkpoint every 2 epochs
  log_interval_steps: 100 # log metrics every 100 training steps

  validator:
    batch_size: 32
    threshold: 0.5


mode: null # mode is set via CLI override (train or test)
checkpoint: null # {run_id}/{checkpoint_tag} e.g. 30925325/best

device: cuda:0
runs_path: ./runs
experiment_name: fcg-detection

# only applied to spectrum. tabular inputs aren't transformed. both transformed spectrum and tabular inputs are tokenized in transformer.
# these are fixed for the most part
# kwargs for auto-instantiation of sequential transformations
eval_transforms:
    - _target_: utils.transforms.Normalizer
      with_std: false

    - _target_: utils.transforms.Resizer
      signal_size: 1024

train_transforms:
    - _target_: utils.transforms.AddNoise
      prob: 0.3
      snr_range: [2, 20]
      mean_noise: 0.0

    - _target_: utils.transforms.Revert
      prob: 0.3

    - _target_: utils.transforms.MaskZeros
      prob: 0.3
      mask_p: [0.01, 0.15]

    - _target_: utils.transforms.ShiftLR
      prob: 0.3
      shift_p: [0.01, 0.1]

    - _target_: utils.transforms.ShiftUD
      prob: 0.3
      shift_p: [0.01, 0.1]

    - _target_: utils.transforms.Normalizer
      with_std: false

    - _target_: utils.transforms.Resizer
      signal_size: 1024