# Models use configs for auto-instantiation of objects, so those have strict structure
defaults:
  - model: ircnn
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null

# The MLFlow run id of the dataset
dataset: 7bb299184c1941ec90459eb11f1409eb

trainer:
  lr: 1e-3
  epochs: 10
  batch_size: 32
  shuffle: True

  checkpoint_interval_epochs: 2 # checkpoint every 2 epochs
  log_interval_steps: 100 # log metrics every 100 training steps

  # needs to be single-threaded if we store dataset in gpu memory
  # for cpu, can speed up by making multithreaded and settings persistent_workers, pin_memory to true
  num_workers: 0
  persistent_workers: False
  pin_memory: False

  validator:
    batch_size: 32
    num_workers: 0
    persistent_workers: False
    pin_memory: False

tester:
  batch_size: 32
  num_workers: 0
  persistent_workers: False
  pin_memory: False


mode: null # mode is set via CLI override (train or test)
checkpoint: null # {run_id}/{checkpoint_filename}
device: cuda:0
runs_path: ./runs
experiment_name: fcg-detection
run_name: ${mode}_${model.name}_${dataset.name}_${now:%Y-%m-%d_%H-%M-%S} # a run is  "mode-model-dataset-time"