# Models use configs for auto-instantiation of objects, so those have strict structure
defaults:
  - model: mt_fcgformer
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null

# for optuna
metric_output_file: null
skip_checkpoints: false

# The MLFlow run id of the dataset
dataset_id: 157d4b53c95f4af88ee86fbcc319bce2
dataset_name: null
fg_names: [alkane, methyl, alkene, alkyne, alcohols, amines, nitriles, aromatics, alkyl halides, esters, ketones, aldehydes, carboxylic acids, ether, acyl halides, amides, nitro]
aux_bool_names: []
aux_float_names: []

run_name: null

# weight accross datasets
# these should probablt be derived for hyperparam opt
nist_weight: 1.0
nist_lser_weight: 0.0

chemmotion_weight: 0.2
chemmotion_lser_weight: 0.00

graphformer_weight: 0.0
graphformer_lser_weight: 0.0

trainer:
  lr: 5e-4
  epochs: 1000
  batch_size: 128
  patience: 20 # stop training if validation loss does not improve for x subsequent epochs
  patience_threshold: 0.1

  initial_aux_bool_weight: 0.5
  initial_aux_float_weight: 0.001
  aux_epochs: 20

  weight_decay: 0.003379

  warmup_steps: 2000

  scheduler_t0: 3
  scheduler_tmult: 2

  checkpoint_interval_epochs: 2 # checkpoint every 2 epochs
  log_interval_steps: 100 # log metrics every 100 training steps

  validator:
    batch_size: 32
    threshold: 0.5


mode: train # mode is set via CLI override (train or test)
checkpoint: null # {run_id}/{checkpoint_tag} e.g. 30925325/best

device: cuda:0
runs_path: ./runs
experiment_name: final_experiment_nist_chem

# only applied to spectrum. tabular inputs aren't transformed. both transformed spectrum and tabular inputs are tokenized in transformer.
# these are fixed for the most part
# kwargs for auto-instantiation of sequential transformations
use_noise: true
use_mask: true
use_shiftud: true
use_shiftlr: false
use_revert: false
