train:
  _target_: datasets.ftir_dataset.FTIRDataset
  data_dir: ./data/ftir
  class_names: [alkane, methyl, alkene, alkyne, alcohols, amines, nitriles, aromatics, alkyl halides, esters, ketones, aldehydes, carboxylic acids, ether, acyl halides, amides, nitro]
  split: train
    
valid:
  _target_: datasets.ftir_dataset.FTIRDataset
  data_dir: ./data/ftir
  class_names: [alkane, methyl, alkene, alkyne, alcohols, amines, nitriles, aromatics, alkyl halides, esters, ketones, aldehydes, carboxylic acids, ether, acyl halides, amides, nitro]
  split: valid

test:
  _target_: datasets.ftir_dataset.FTIRDataset
  data_dir: ./data/ftir
  class_names: [alkane, methyl, alkene, alkyne, alcohols, amines, nitriles, aromatics, alkyl halides, esters, ketones, aldehydes, carboxylic acids, ether, acyl halides, amides, nitro]
  split: test

eval_transforms:
    - _target_: utils.transforms.Normalizer
      with_std: false

    - _target_: utils.transforms.Resizer
      signal_size: 1024

train_transforms:
    - _target_: utils.transforms.AddNoise
      prob: 0.3
      snr_range: [2, 20]
      mean_noise: 0.0

    - _target_: utils.transforms.Revert
      prob: 0.3

    - _target_: utils.transforms.MaskZeros
      prob: 0.3
      mask_p: [0.01, 0.15]

    - _target_: utils.transforms.ShiftLR
      prob: 0.3
      shift_p: [0.01, 0.1]

    - _target_: utils.transforms.ShiftUD
      prob: 0.3
      shift_p: [0.01, 0.1]

    - _target_: utils.transforms.Normalizer
      with_std: false

    - _target_: utils.transforms.Resizer
      signal_size: 1024
