train:
  _target_: datasets.ftir_dataset.FTIRDataset
  data_dir: ./data/ftir
  class_names: [alkane, methyl, alkene, alkyne, alcohols, amines, nitriles, aromatics, alkyl halides, esters, ketones, aldehydes, carboxylic acids, ether, acyl halides, amides, nitro]
  split: train

valid:
  _target_: datasets.ftir_dataset.FTIRDataset
  data_dir: ./data/ftir
  class_names: [alkane, methyl, alkene, alkyne, alcohols, amines, nitriles, aromatics, alkyl halides, esters, ketones, aldehydes, carboxylic acids, ether, acyl halides, amides, nitro]
  split: valid

test:
  _target_: datasets.ftir_dataset.FTIRDataset
  data_dir: ./data/ftir
  class_names: [alkane, methyl, alkene, alkyne, alcohols, amines, nitriles, aromatics, alkyl halides, esters, ketones, aldehydes, carboxylic acids, ether, acyl halides, amides, nitro]
  split: test